name: Portfolio Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /var/www/html/portfolio
          git pull origin master

      - name: Install dependencies
        run: |
          cd /var/www/html/portfolio
          npm ci

      - name: Build app
        run: |
          cd /var/www/html/portfolio
          npm run build
